# Generated by Django 5.1.2 on 2024-11-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
