# Generated by Django 5.1.2 on 2024-10-17 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_brand_is_listed_collection_is_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default=datetime.datetime(2024, 10, 17, 12, 32, 19, 525113, tzinfo=datetime.timezone.utc), upload_to='uploads/product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=datetime.datetime(2024, 10, 17, 12, 32, 27, 477651, tzinfo=datetime.timezone.utc), upload_to='uploads/product'),
            preserve_default=False,
        ),
    ]
