# Generated by Django 5.1.2 on 2024-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_product_image1_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default=32, max_length=3),
            preserve_default=False,
        ),
    ]
