# Generated by Django 5.1.2 on 2024-11-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_coupen_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='usage_limit',
            field=models.IntegerField(default=3),
        ),
    ]
