# Generated by Django 5.1.2 on 2024-11-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_coupen_usage_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
