# Generated by Django 5.1.2 on 2024-10-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
