# Generated by Django 5.1.2 on 2024-10-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_product_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
