# Generated by Django 5.1.2 on 2024-10-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_product_description1_product_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_path',
        ),
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='product',
            name='freequency',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='product',
            name='power_reserve',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='product',
            name='water_resistance',
            field=models.IntegerField(default=10),
        ),
    ]
