# Generated by Django 5.1.2 on 2024-10-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_product_video_path_product_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
