# Generated by Django 5.1.2 on 2024-11-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
