# Generated by Django 5.1.2 on 2024-11-19 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_order_discounted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 11, 19, 3, 3, 15, 67438, tzinfo=datetime.timezone.utc), upload_to='uploads/brands'),
            preserve_default=False,
        ),
    ]
