# Generated by Django 5.1.2 on 2024-10-25 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_product_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_slider',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.product'),
        ),
    ]
