# Generated by Django 5.1.2 on 2024-11-19 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_image',
            field=models.ImageField(default=datetime.datetime(2024, 11, 19, 3, 47, 30, 560526, tzinfo=datetime.timezone.utc), upload_to='uploads/brands/banner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_image',
            field=models.ImageField(default=datetime.datetime(2024, 11, 19, 3, 47, 34, 190710, tzinfo=datetime.timezone.utc), upload_to='uploads/brands/logo'),
            preserve_default=False,
        ),
    ]
