# Generated by Django 5.1.2 on 2024-11-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_brand_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='discription',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
