# Generated by Django 5.1.2 on 2024-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_brand_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='min_required',
            field=models.IntegerField(default=1000),
        ),
    ]
