# Generated by Django 5.1.2 on 2024-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_slider',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='uploads/product_slider'),
        ),
    ]
