# Generated by Django 5.1.2 on 2024-11-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_product_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_slider',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/product_slider'),
        ),
    ]
