# Generated by Django 5.1.2 on 2024-11-27 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_alter_product_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_slider',
            name='image',
            field=models.FileField(default=datetime.datetime(2024, 11, 27, 3, 22, 28, 776199, tzinfo=datetime.timezone.utc), upload_to='uploads/product_slider'),
            preserve_default=False,
        ),
    ]
