# Generated by Django 5.1.2 on 2024-11-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_delete_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cod', 'Cod'), ('pwallet', 'Personal Wallet'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=8),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
