# Generated by Django 5.1.2 on 2024-11-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
