# Generated by Django 5.1.2 on 2024-12-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0032_transactionhistory_delete_personalwallettransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
