# Generated by Django 5.1.2 on 2024-12-03 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=datetime.datetime(2024, 12, 3, 8, 59, 58, 153757, tzinfo=datetime.timezone.utc), null=True, upload_to='uploads/profile'),
        ),
    ]
