# Generated by Django 5.1.2 on 2024-12-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='uploads/profile/salamanedthephoto_DXAOlYb.jpg', null=True, upload_to='uploads/profile'),
        ),
    ]
