# Generated by Django 5.1.2 on 2024-10-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
