# Generated by Django 5.1.2 on 2024-10-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='max_otp_try',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_max_out',
        ),
    ]
